POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOjIsImlhdCI6MTcyODIyNjcyM30.r1CnrEbxs2FXDlu6lvgloGp_81NaogkTMlPgiBmWKP8

{
    "author": "Richard Couzens",
    "url": "https://BichardBouzensFanSite.com",
    "title": "Bichard Bouzens Fan Site"
}
